#!/usr/bin/env node
/**
 * Keeps everything that has to know the locale list in agreement with
 * `rosey.yml`, which is the single source of truth.
 *
 * Two things need syncing when a locale is added or removed:
 *
 *   1. `src/rosey/locales/<code>.json` must exist. `write-locales` creates it
 *      during a build, but CloudCannon has to be able to open the file in the
 *      editor before any build has run.
 *
 *   2. `cloudcannon.config.yml` needs a `data_config.locales_<code>` entry.
 *      The connector discovers locale data via `api.dataset("locales_<code>")`,
 *      so the `locales_` prefix and the exact code are both mandatory — without
 *      the entry the locale simply does not appear in the editor's switcher.
 *
 * The config file is edited between marker comments rather than parsed and
 * re-dumped: js-yaml discards comments, and cloudcannon.config.yml is a
 * hand-maintained file that is mostly comments. Everything outside the markers
 * is preserved byte for byte.
 *
 * Usage:
 *   node ./utils/syncRoseyLocales.js          write the changes
 *   node ./utils/syncRoseyLocales.js --check  exit 1 if anything is out of date
 */
const fs = require("fs");
const path = require("path");
const yaml = require("js-yaml");

const ROOT = path.join(__dirname, "..");
const ROSEY_CONFIG = path.join(ROOT, "rosey.yml");
const CC_CONFIG = path.join(ROOT, "cloudcannon.config.yml");

const START_MARKER =
  "  # rosey:locales:start — generated by `npm run rosey:sync`. Do not edit by hand.";
const END_MARKER = "  # rosey:locales:end";

const checkOnly = process.argv.includes("--check");
const problems = [];

function readRoseyConfig() {
  const config = yaml.load(fs.readFileSync(ROSEY_CONFIG, "utf8"));
  if (!config || typeof config !== "object") {
    throw new Error(`${ROSEY_CONFIG} is empty or not a mapping.`);
  }
  return config;
}

const config = readRoseyConfig();
const localesSetting = (config.locales || "src/rosey/locales").replace(/\/+$/, "");
const localesDir = path.join(ROOT, localesSetting);

/**
 * `data_config` paths are resolved against cloudcannon.config.yml's `source`,
 * which this repo sets to `src`. Rosey knows the locales directory only as a
 * repo-root path, so strip the source prefix before writing an entry, or
 * CloudCannon would look for `src/src/rosey/locales/en.json`.
 */
function toSourceRelative(repoRelativePath) {
  let ccSource = "";
  try {
    const ccConfig = yaml.load(fs.readFileSync(CC_CONFIG, "utf8"));
    ccSource = ((ccConfig && ccConfig.source) || "").replace(/^\/+|\/+$/g, "");
  } catch (error) {
    ccSource = "";
  }
  if (!ccSource) {
    return repoRelativePath;
  }
  const prefix = `${ccSource}/`;
  if (!repoRelativePath.startsWith(prefix)) {
    throw new Error(
      `rosey.yml has \`locales: ${repoRelativePath}\`, which is outside ` +
        `cloudcannon.config.yml's \`source: ${ccSource}\`. CloudCannon cannot ` +
        `address it, so editors would not be able to open any locale file. ` +
        `Move the directory under ${ccSource}/ or remove the \`source\` key.`,
    );
  }
  return repoRelativePath.slice(prefix.length);
}

const localesDirRelative = toSourceRelative(localesSetting);
const languages = Array.isArray(config.languages)
  ? config.languages.filter(Boolean).map((locale) => String(locale).trim())
  : [];

// A locale code has to survive being a filename, a URL segment and half of a
// `data_config` key, so reject anything that is not a plain BCP 47-ish code
// rather than writing a file called `../../etc/passwd.json`.
const INVALID = languages.filter((locale) => !/^[A-Za-z]{2,3}(-[A-Za-z0-9]{2,8})*$/.test(locale));
if (INVALID.length) {
  console.error(
    `[rosey:sync] Invalid locale code(s) in rosey.yml: ${INVALID.join(", ")}\n` +
      `             Expected codes like "es", "pt-BR" or "zh-Hans".`,
  );
  process.exit(1);
}

/* ------------------------------------------------------------------ *
 * 1. Locale JSON files
 * ------------------------------------------------------------------ */

fs.mkdirSync(localesDir, { recursive: true });

// `rosey build` has no language filter: it builds one copy of the site for every
// file in the locales directory. The directory IS the language list, so keeping
// it equal to `languages` is what makes rosey.yml authoritative.
const DISABLED_DIR = path.join(path.dirname(localesDir), "locales-disabled");

for (const locale of languages) {
  const localeFile = path.join(localesDir, `${locale}.json`);
  if (fs.existsSync(localeFile)) {
    continue;
  }
  const archived = path.join(DISABLED_DIR, `${locale}.json`);
  if (checkOnly) {
    problems.push(`missing locale file ${path.relative(ROOT, localeFile)}`);
    continue;
  }
  if (fs.existsSync(archived)) {
    // Re-enabling a locale that was turned off earlier: its translations come
    // back with it.
    fs.mkdirSync(localesDir, { recursive: true });
    fs.renameSync(archived, localeFile);
    console.log(`[rosey:sync] Restored ${path.relative(ROOT, localeFile)} from locales-disabled/`);
    continue;
  }
  // `write-locales` fills this in from base.json on the next build. An empty
  // object is a valid locale file in the meantime.
  fs.writeFileSync(localeFile, "{}\n");
  console.log(`[rosey:sync] Created ${path.relative(ROOT, localeFile)}`);
}

// Locales dropped from `languages` are ARCHIVED, not deleted. Deleting would
// throw away every translation in the file the moment someone edits one line of
// config; leaving it in place would keep Rosey building and publishing a locale
// that the config no longer lists. Moving it aside stops the build and keeps the
// work, and adding the code back restores it.
const liveLocaleFiles = fs.existsSync(localesDir)
  ? fs.readdirSync(localesDir).filter((file) => file.endsWith(".json"))
  : [];

for (const file of liveLocaleFiles) {
  const locale = file.slice(0, -".json".length);
  if (languages.includes(locale)) {
    continue;
  }
  if (checkOnly) {
    problems.push(
      `${path.relative(ROOT, path.join(localesDir, file))} is not in rosey.yml's \`languages\` ` +
        `(it would still be built and published)`,
    );
    continue;
  }
  fs.mkdirSync(DISABLED_DIR, { recursive: true });
  fs.renameSync(path.join(localesDir, file), path.join(DISABLED_DIR, file));
  console.log(
    `[rosey:sync] Archived ${path.relative(ROOT, path.join(localesDir, file))} ` +
      `-> locales-disabled/ (removed from \`languages\`; translations kept)`,
  );
}

/* ------------------------------------------------------------------ *
 * 2. cloudcannon.config.yml data_config block
 * ------------------------------------------------------------------ */

function renderDataConfig() {
  if (!languages.length) {
    return [
      START_MARKER,
      "  # No locales configured. Add them to `languages` in rosey.yml, then run",
      "  # `npm run rosey:sync` to generate an entry for each one here.",
      END_MARKER,
    ].join("\n");
  }
  const entries = languages.flatMap((locale) => [
    `  locales_${locale}:`,
    `    path: ${localesDirRelative}/${locale}.json`,
  ]);
  return [START_MARKER, ...entries, END_MARKER].join("\n");
}

const ccSource = fs.readFileSync(CC_CONFIG, "utf8");
const startIndex = ccSource.indexOf(START_MARKER);
const endIndex = ccSource.indexOf(END_MARKER);

if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
  console.error(
    `[rosey:sync] Could not find the generated block in ${path.relative(ROOT, CC_CONFIG)}.\n` +
      `             Expected these two lines under a top-level \`data_config:\` key:\n` +
      `${START_MARKER}\n${END_MARKER}`,
  );
  process.exit(1);
}

const before = ccSource.slice(0, startIndex);
const after = ccSource.slice(endIndex + END_MARKER.length);
const updated = `${before}${renderDataConfig()}${after}`;

if (updated !== ccSource) {
  if (checkOnly) {
    problems.push(`${path.relative(ROOT, CC_CONFIG)} data_config is out of date`);
  } else {
    fs.writeFileSync(CC_CONFIG, updated);
    console.log(`[rosey:sync] Updated data_config in ${path.relative(ROOT, CC_CONFIG)}`);
  }
}

/* ------------------------------------------------------------------ *
 * 3. Report
 * ------------------------------------------------------------------ */

if (checkOnly && problems.length) {
  console.error(
    "[rosey:sync] Out of sync with rosey.yml:\n" +
      problems.map((problem) => `  - ${problem}`).join("\n") +
      "\n\nRun `npm run rosey:sync` to fix.",
  );
  process.exit(1);
}

const summary = languages.length ? languages.join(", ") : "none";
console.log(`[rosey:sync] ${checkOnly ? "In sync" : "Synced"}. Original: ${config.default_language}. Translations: ${summary}.`);
